{
  checkThread();
  try {
    Assert.fail(message);
  }
 catch (  AssertionError e) {
    handleThrowable(e);
  }
}
