{
  if (awaitCalled) {
    throw new IllegalStateException("await() already called");
  }
  awaitCalled=true;
  try {
    boolean ok=latch.await(delay,timeUnit);
    if (!ok) {
      throw new IllegalStateException("Timed out in waiting for test complete");
    }
 else {
      if (throwable != null) {
        if (throwable instanceof Error) {
          throw (Error)throwable;
        }
 else         if (throwable instanceof RuntimeException) {
          throw (RuntimeException)throwable;
        }
 else {
          throw new IllegalStateException(throwable);
        }
      }
    }
  }
 catch (  InterruptedException e) {
    throw new IllegalStateException("Test thread was interrupted!");
  }
}
