{
  if (tearingDown) {
    throw new IllegalStateException("assert or failure occurred after test has completed");
  }
  throwable=t;
  thrownThread=Thread.currentThread();
  latch.countDown();
  if (t instanceof AssertionError) {
    throw (AssertionError)t;
  }
}
