{
  try {
    Assert.assertNotSame(unexpected,actual);
  }
 catch (  AssertionError e) {
    handleThrowable(e);
  }
}
